name: Build astroarch

on:
  push:
    branches:
    - workflows

jobs:
  build-astroarch:
    name: "Build"
    runs-on: ["self-hosted"]
    container:
      image: ghcr.io/devducks/archlinuxarm:latest
    timeout-minutes: 15
    steps:
      - name: Bootstrap pacman keyring
        run: pacman-key --init && pacman-key --populate archlinuxarm && pacman -Syu --noconfirm

      - uses: actions/checkout@v4

      - name: astroarch
        run: bash ci/astroarch_build.sh

